#!/usr/bin/env bash
# displays numbers from 1 to 100, and also display:
#	FizzBuzz when the number is a multiple of 3 and 5
#	Fizz when the number is multiple of 3
#	Buzz when the number is a multiple of 5

count=1
while [ $count -ne 101 ]
do
    if [ $((count % 15)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((count % 3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $((count % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
	echo $count
    fi
    ((count++))
done
